version: '2'

services:
  tmweb:
    build: ./transmart-web
    ports:
      - "127.0.0.1:8888:80"
    depends_on:
      - tmapp
  tmapp:
    build: ./transmart-app
    depends_on:
      - tmdb
      - tmsolr
  tmdb:
    build: ./transmart-db
    ports:
      - "127.0.0.1:5432:5432"
  tmsolr:
    build: ./transmart-solr
  tmrserve:
    build: ./transmart-rserve
    volumes_from:
      - tmapp
  tmload:
    build: ./transmart-load
    depends_on:
      - tmdb
