version: '3.5'

services:

  tmapp-app2:
    image: kretzlerdevs/transmart-app:1.0
    restart: unless-stopped
    expose:
      - 8080
    env_file:
      - ${ENV_FILE_APP2}
    depends_on:
      - tmdb-app2
      - tmsolr-app2
      - tmrserve-app2
    networks:
      default:
        aliases:
          - tmapp-app2
    volumes:
      - "${DOCKER_APP_CONFIG_DIR_APP2}/Config.groovy:/usr/local/tomcat/.grails/transmartConfig/Config.groovy"
      - "${DOCKER_APP_CONFIG_DIR_APP2}/NEPTUNE_tranSMART_Quick_Start_Guide.pdf:/usr/local/tomcat/files/NEPTUNE_tranSMART_Quick_Start_Guide.pdf"
      - "./transmart-app/DataSource.groovy:/usr/local/tomcat/.grails/transmartConfig/DataSource.groovy"
      - "./transmart-app/setenv.sh:/usr/local/tomcat/bin/setenv.sh"
      - "appdata-app2:/root/.grails"
      - "apptmp-app2:/tmp"
      - "./transmart-app/Rscripts:/Rscripts"     
      - "appwebapps-app2:/usr/local/tomcat/webapps"
      - "appweblogs-app2:/usr/local/tomcat/logs"

  tmdb-app2:
    image: kretzlerdevs/transmart-db:1.0
    restart: unless-stopped
    ports:
      - ${DOCKER_DB_PORT_APP2:-5432}:5432   
    expose:
      - 5432
    env_file:
      - ${ENV_FILE_APP2}
    networks:
      default:
        aliases:
          - tmdb-app2
    volumes:
      - "postgresdata-app2:/var/lib/postgresql"
      - "postgreslogs-app2:/var/log/postgresql"

  tmsolr-app2:
    image: transmartfoundation/transmart-solr:latest
    restart: unless-stopped
    expose:
      - 8983
    env_file:
      - ${ENV_FILE_APP2}
    networks:
      default:
        aliases:
          - tmsolr-app2
      

  tmrserve-app2:
    image: transmartfoundation/transmart-rserve:latest
    restart: unless-stopped
    expose:
      - 6311
    env_file:
      - ${ENV_FILE_APP2}
    volumes:
      - "apptmp-app2:/tmp"
      - "./transmart-app/Rscripts:/Rscripts"
    networks:
      default:
        aliases:
          - tmrserve-app2
      

volumes:
  appdata-app2:
  apptmp-app2:
  appwebapps-app2:
  appweblogs-app2:
  postgresdata-app2:
  postgreslogs-app2:

networks:
  default: 
    name: transmart    
    external: true
