version: '3.5'

services:
  tmweb:
    image: httpd:2.4-alpine
    restart: unless-stopped
    network_mode: host
    depends_on:
      - tmapp
    expose:
      - 80
      - 443
    env_file:
      - ${ENV_FILE}
    volumes:
      - "./transmart-web/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf"
      - "./transmart-web/httpd.conf:/usr/local/apache2/conf/httpd.conf"
  tmapp:
    image: transmartfoundation/transmart-app:latest
    restart: unless-stopped
    expose:
      - 8009
      - 8080
    ports:
      - ${DOCKER_TOMCATAJP_PORT:-8009}:8009
      - ${DOCKER_TOMCAT_PORT:-8080}:8080
    env_file:
      - ${ENV_FILE}
    depends_on:
      - tmdb
      - tmsolr
    volumes:
      - "./transmart-app/Config.groovy:/usr/local/tomcat/.grails/transmartConfig/Config.groovy"
      - "./transmart-app/DataSource.groovy:/usr/local/tomcat/.grails/transmartConfig/DataSource.groovy"
      - "./transmart-app/setenv.sh:/usr/local/tomcat/bin/setenv.sh"
      - "appdata:/root/.grails"
      - "apptmp:/tmp"
      - "appwebapps:/usr/local/tomcat/webapps"
  tmdb:
    image: transmartfoundation/transmart-db:latest
    restart: unless-stopped
    expose:
      - 5432
    ports:
      - ${DOCKER_DB_PORT:-5432}:5432
    env_file:
      - ${ENV_FILE}
    volumes:
      - "postgresdata:/var/lib/postgresql"
      - "postgreslogs:/var/log/postgresql"
  tmsolr:
    image: transmartfoundation/transmart-solr:latest
    restart: unless-stopped
    expose:
      - 8983
    ports:
      - ${DOCKER_SOLR_PORT:-8983}:8983
    env_file:
      - ${ENV_FILE}
  tmrserve:
    image: transmartfoundation/transmart-rserve:latest
    restart: unless-stopped
    expose:
      - 6311
    ports:
      - ${DOCKER_RSERVE_PORT:-6311}:6311
    env_file:
      - ${ENV_FILE}
    volumes:
      - "apptmp:/tmp"
  tmload:
    image: transmartfoundation/transmart-load:latest
    depends_on:
      - tmdb
    env_file:
      - ${ENV_FILE}

volumes:
  appdata:
  apptmp:
  appwebapps:
  postgresdata:
  postgreslogs:
