version: '3.5'

services:
  tmweb:
    image: httpd:2.4-alpine
    restart: unless-stopped
    depends_on:
      - tmapp
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ${ENV_FILE}
    volumes:
      - "./transmart-web/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf"
      - "./transmart-web/httpd.conf:/usr/local/apache2/conf/httpd.conf"
    networks:
      transmart:
        aliases:
          - tmweb

  tmapp:
    image: kretzlerdevs/transmart-app:1.0
    restart: unless-stopped
    ports:
      - 8080
    env_file:
      - ${ENV_FILE}
    depends_on:
      - tmdb
      - tmsolr
      - tmrserve
    networks:
      transmart:
        aliases:
          - tmapp
    volumes:
      - "./transmart-app/Config.groovy:/usr/local/tomcat/.grails/transmartConfig/Config.groovy"
      - "./transmart-app/DataSource.groovy:/usr/local/tomcat/.grails/transmartConfig/DataSource.groovy"
      - "./transmart-app/setenv.sh:/usr/local/tomcat/bin/setenv.sh"
      - "appdata:/root/.grails"
      - "apptmp:/tmp"
      - "appwebapps:/usr/local/tomcat/webapps"
      - "appweblogs:/usr/local/tomcat/logs"

  tmdb:
    image: kretzlerdevs/transmart-db:1.0
    restart: unless-stopped
    expose:
      - 5432
    ports:
      - ${DOCKER_DB_PORT:-5432}:5432
    env_file:
      - ${ENV_FILE}
    networks:
      transmart:
        aliases:
          - tmdb
    volumes:
      - "postgresdata:/var/lib/postgresql"
      - "postgreslogs:/var/log/postgresql"

  tmsolr:
    image: transmartfoundation/transmart-solr:latest
    restart: unless-stopped
    expose:
      - 8983
    ports:
      - ${DOCKER_SOLR_PORT:-8983}:8983
    env_file:
      - ${ENV_FILE}
    networks:
      - transmart

  tmrserve:
    image: transmartfoundation/transmart-rserve:latest
    restart: unless-stopped
    expose:
      - 6311
    ports:
      - ${DOCKER_RSERVE_PORT:-6311}:6311
    env_file:
      - ${ENV_FILE}
    volumes:
      - "apptmp:/tmp"
      - "./transmart-app/Rscripts:/tmp/Rscripts"
    networks:
      - transmart
  
  tmload:
    image: transmartfoundation/transmart-load:latest
    depends_on:
      - tmdb
    env_file:
      - ${ENV_FILE}
    networks:
      - transmart

volumes:
  appdata:
  apptmp:
  appwebapps:
  appweblogs:
  postgresdata:
  postgreslogs:

networks:
  transmart:
