version: '3.5'

services:
  tmweb:
    image: httpd:alpine
    restart: unless-stopped
    depends_on:
      - tmapp
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ./.env
    volumes:
      - "./transmart-web/${V_HOSTS_FILE}:/usr/local/apache2/conf/extra/httpd-vhosts.conf"
      - "./transmart-web/httpd.conf:/usr/local/apache2/conf/httpd.conf"
      - "${DOCKER_APP_DOCS_DIR}:/usr/local/apache2/htdocs/files"
      - "./transmart-web/certs:/etc/apache2/certs"
    networks:
      default:
        aliases:
          - tmweb


  tmapp:
    image: kretzlerdevs/transmart-app:1.0
    restart: unless-stopped
    ports:
      - 8080
    env_file:
      - ${ENV_FILE}
    depends_on:
      - tmdb
      - tmsolr
      - tmrserve
    networks:
      default:
         aliases:
          - tmapp
    volumes:
      - "${DOCKER_APP_CONFIG_DIR}/Config.groovy:/usr/local/tomcat/.grails/transmartConfig/Config.groovy"
      - "${DOCKER_APP_DOCS_DIR}/:/usr/local/tomcat/webapps/files/"
      - "./transmart-app/DataSource.groovy:/usr/local/tomcat/.grails/transmartConfig/DataSource.groovy"
      - "./transmart-app/setenv.sh:/usr/local/tomcat/bin/setenv.sh"
      - "appdata:/root/.grails"
      - "apptmp:/tmp"
      - "appwebapps:/usr/local/tomcat/webapps"
      - "appweblogs:/usr/local/tomcat/logs"
      - './transmart-app/Rscripts:/tmp/Rscripts'

  tmdb:
    image: kretzlerdevs/transmart-db:1.0
    restart: unless-stopped
    user: postgres
    expose:
      - 5432
    ports:
      - ${DOCKER_DB_PORT:-5432}:5432
    env_file:
      - ${ENV_FILE}
    networks:
      default:
         aliases:
          - tmdb
    volumes:
      - "postgresdata:/var/lib/postgresql"
      - "postgreslogs:/var/log/postgresql"

  tmsolr:
    image: transmartfoundation/transmart-solr:latest
    restart: unless-stopped
    expose:
      - 8983
    ports:
      - ${DOCKER_SOLR_PORT:-8983}:8983
    env_file:
      - ${ENV_FILE}
    networks:
      default:
         aliases:
          - tmsolr

  tmrserve:
    image: transmartfoundation/transmart-rserve:latest
    restart: unless-stopped
    expose:
      - 6311
    ports:
      - ${DOCKER_RSERVE_PORT:-6311}:6311
    env_file:
      - ${ENV_FILE}
    volumes:
      - "apptmp:/tmp"
      - "./transmart-app/Rscripts:/tmp/Rscripts"
    networks:
      default:
         aliases:
          - tmrserve


  tmload:
    image: transmartfoundation/transmart-load:latest
    depends_on:
      - tmdb
    env_file:
      - ${ENV_FILE}
    networks:
      default:
         aliases:
          - tmload

volumes:
  appdata:
  apptmp:
  appwebapps:
  appweblogs:
  postgresdata:
  postgreslogs:

networks:
  default:
    name: transmart
